baseURL = 'https://bhuv.live'
languageCode = 'en-us'
title = "bhuv's notebook"
theme = "paper"
name = "Bhuvanesh"

[params]

monoDarkIcon = true # show monochrome dark mode icon

twitter = "_bhuvanesh_"
linkedin = "bhuvanesh-sridharan-40887b19b/"
github = "bhuvanesh09"

name = "Bhuvanesh Sridharan"
bio = "ML Engineer at Sprinklr"

mainSections = ["home", "posts"]


[menu]
main = [
    { name = "About", url = "/about" },
    { name = "ThoughtDrops", url = "/posts" },
    { name = "Publications", url = "/publications" },
]


[markup.goldmark.renderer]
unsafe = true
