baseURL = 'https://bhuv.live'
googleAnalytics = 'G-TJGSXWPJT4'
languageCode = 'en-us'
title = "bhuv's notebook"
theme = ["hugo-notice", "paper"]
name = "Bhuvanesh"

[params]

monoDarkIcon = true                                # show monochrome dark mode icon
color = "linen"
google_fonts = "family=Inter:opsz,wght@14..32,500"

twitter = "_bhuvanesh_"
linkedin = "bhuvanesh-sridharan-40887b19b/"
github = "bhuvanesh09"

name = "Bhuvanesh Sridharan"
bio = "ML Engineer at Sprinklr"

mainSections = ["home", "posts"]


[menu]
main = [
    { name = "About", url = "/about" },
    { name = "Blogs", url = "/posts" },
    { name = "Publications", url = "/publications" },
]


[markup.goldmark.renderer]
unsafe = true
